-- =======================================================
-- TradePilot AI - Schema PostgreSQL para o Supabase
-- Executar no SQL Editor do Supabase Dashboard
-- =======================================================

CREATE TABLE IF NOT EXISTS tradepilot_setups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    symbol VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL, -- 'BUY' ou 'SELL'
    alert_type VARCHAR(20) NOT NULL, -- 'PRE_ALERT', 'ENTRY_ELIGIBLE'
    total_score INT NOT NULL,
    entry_price NUMERIC(18, 8) NOT NULL,
    stop_loss NUMERIC(18, 8) NOT NULL,
    take_profit_1 NUMERIC(18, 8) NOT NULL,
    take_profit_2 NUMERIC(18, 8) NOT NULL,
    rr_ratio NUMERIC(6, 2) NOT NULL,
    score_breakdown JSONB,
    technical_reasons JSONB,
    risk_factors JSONB,
    poi_low NUMERIC(18, 8),
    poi_high NUMERIC(18, 8),
    has_fvg BOOLEAN DEFAULT FALSE,
    has_sweep BOOLEAN DEFAULT FALSE,
    outcome VARCHAR(20) DEFAULT 'PENDING', -- 'PENDING', 'WIN_TP1', 'WIN_TP2', 'STOPPED'
    result_r NUMERIC(6, 2) DEFAULT 0.0
);

-- Índices para otimização de performance em consultas do Dashboard
CREATE INDEX IF NOT EXISTS idx_setups_symbol ON tradepilot_setups(symbol);
CREATE INDEX IF NOT EXISTS idx_setups_alert_type ON tradepilot_setups(alert_type);
CREATE INDEX IF NOT EXISTS idx_setups_created_at ON tradepilot_setups(created_at DESC);

-- Permissão de escrita e leitura (desativa o bloqueio RLS para inserções do bot)
ALTER TABLE tradepilot_setups DISABLE ROW LEVEL SECURITY;
